### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by penyuan** [Evolving-AI-Lab/deep_learning_for_camera_trap_images#1]
Just learned about this project, amazing work!

Can you attach a license to this repo and [this one](https://github.com/arashno/tensorflow_multigpu_imagenet) and [this one](https://github.com/arashno/tensorflow_multigpu_imagenet)? Such as GPLv3+? Thanks!

**Comment by arashno** [comment]
Now both repositories have a license attached to them.
