### ISSUE TITLE
EF_val.csv - how to get?

### ISSUE THREAD

**Issue by sriki77** [Evolving-AI-Lab/deep_learning_for_camera_trap_images#2]
I was trying to run your code with pre-trained model.

Where can i find EF_val.csv.

Please let me know.

**Comment by arashno** [comment]
Build your own!
Here is a sample:
val/empty/S2_G04_R1_PICT1466.JPG,0
val/empty/S5_P03_R3_IMAG1969.JPG,0
val/empty/S3_I12_R12_IMAG3081.JPG,0
val/empty/S2_D10_R2_PICT4785.JPG,0
val/full/S6_I01_R2_IMAG0159.JPG,1
val/empty/S6_F08_R2_IMAG2119.JPG,0
val/empty/S3_D07_R11_IMAG4157.JPG,0
val/full/S5_D03_R2_IMAG0218.JPG,1
val/empty/S6_C05_R1_IMAG3511.JPG,0
val/empty/S1_G11_R1_PICT2039.JPG,0
val/full/S3_R06_R11_IMAG0641.JPG,1
val/empty/S1_L05_R1_PICT1388.JPG,0
val/empty/S6_Q10_R2_IMAG1036.JPG,0
val/full/S4_S11_R2_IMAG2731.JPG,1
val/full/S5_J02_R3_IMAG0971.JPG,1
val/empty/S4_J07_R2_IMAG2394.JPG,0
val/empty/S4_D11_R2_IMAG1851.JPG,0
val/full/S5_T13_R3_IMAG4032.JPG,1
val/empty/S6_D13_R1_IMAG4276.JPG,0
val/empty/S6_P13_R2_IMAG1574.JPG,0
